export interface IFormControl {
    displayName: string
    dbName: string // can be an ID or database assigned name that differs from the display name (autogenerated SharePoint name)
    type: FormControlType
    metadata?: any // any extra data that does not fit into given fields i.e. choices for choice column
    defaultValue?: any
    displayOnly?: boolean
    required?: boolean
}

export type FormControlType = "text" | "choice" | "checkbox" | "textarea" | "datetime" | "number"
