export interface IWork {
    Id: number
    Title?: string
    submitterId?: string
    approved?: any
    type?: string
    course?: string
    format?: string
    authorName?: string
    artist?: string
    publisher?: string
    yearPublished?: string
    seriesTitle?: any
    albumTitle?: any
    bookTitle?: any
    journalTitle?: string
    edition?: string
    formatInformation?: string
    callNumber?: string
    ISSN?: any
    ISBN?: string
    volume?: any
    issue?: any
    pageRange?: any
    totalPages?: string
    totalChapters?: any
    URL?: string
    holdType?: any
    holdFrom?: any
    holdUntil?: any
    year?: any
    director?: any
    hardCopyOwner?: string
}
